### ISSUE TITLE
Images in the component no showing when exported jpeg and pdf

### ISSUE THREAD

**Issue by Nijinsha** [salman-monetate/react-component-export-image#13]
I have some images in the component exported loaded from firebase storage which is not showing up when exported

**Comment by salman-monetate** [comment]
Is it svg?

`react-component-export-image` uses `html2Canvas`, this issue is open there

https://github.com/niklasvh/html2canvas/issues/1543

Also in one of the comments it says if you add width and height to the svg it works, can you please try and let me know. If it still doesn't work, can look for the alternative.

**Comment by Nijinsha** [comment]
The fix works. Thanks
